global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: node_api
    static_configs:
      - targets: ["node-api:3001"]
    metrics_path: /metrics

  - job_name: rust_api
    static_configs:
      - targets: ["rust-api:3002"]
    metrics_path: /metrics

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - source_labels: [name]
        regex: ".*node-rust-equivalent-(node|rust)-api"
        action: keep
